// flow-typed signature: 3dad6ac9c12fa23e34d37552a48d19cc
// flow-typed version: <<STUB>>/koa-session_v^3.4.0/flow_v0.36.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-session'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the 
 * community by sending a pull request to: 
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-session' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'koa-session/index' {
  declare module.exports: $Exports<'koa-session'>;
}
declare module 'koa-session/index.js' {
  declare module.exports: $Exports<'koa-session'>;
}
